import { getRolesApi } from "@/core/api/rol/getRoles"
import { useEffect, useState } from "react"
import { toast } from "./use-toast"

// Generated by https://quicktype.io

export interface RolResponse {
  id: number
  nombre: string
}

const useRoles = () => {
  const [roles, setRoles] = useState<RolResponse[]>()

  useEffect(() => {
    const fetchRoles = async () => {
      try {
        const data = await getRolesApi() 

        if(!data){
          toast({
            title: "No hay Roles de Usuario disponibles",
            variant: "destructive"
          })
          return
        }

        setRoles(data)
      } catch (error) {
        toast({
          title: "No se ha logrado encontrar los roles",
          description: `${error}`
        })
      }
    }

    fetchRoles()
  }, [])

  return {
    roles
  }
}
export default useRoles
