import { erragonApi } from "../erragonApi"

// Generated by https://quicktype.io

export interface PromptResponse {
  prompt: string;
}


export const getPrompt = async(): Promise<PromptResponse | null> => {
  try {
      const {data} = await erragonApi.get<PromptResponse>("/prompt")

      if(!data) return null

      return data
  } catch (error) {
    console.error(error)
    return null
  }
}